[package]
name = "btc_feed"
version = "0.0.0"
authors = ["Albert Hermida <albert@switchboard.xyz>"]
edition = "2023_10"
cairo-version = "2.8.4"
scarb-version = "2.8.4"

[dependencies]
starknet = ">=2.8.4"
openzeppelin_token = "0.19.0"
switchboard = { git = "https://github.com/switchboard-xyz/starknet.git" }

[lib]

[tool.fmt]
max_line_length = 120
sort-module-level-items = true
tab_size = 2

[dev-dependencies]
cairo_test = "2.8.0"

[[target.starknet-contract]]